variables:
  TEST_SCOPE: ""
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'web'
    
stages:
  # - install
  - test
  - report
  - upload
  - notify

# install_dependencies:
#   image: 149062447078.dkr.ecr.ap-southeast-1.amazonaws.com/cicd/qa-base:production
#   stage: install
#   script:
#     - echo "install de"
#   artifacts:
#     paths:
#       - node_modules/

run_tests:
  image: 149062447078.dkr.ecr.ap-southeast-1.amazonaws.com/cicd/qa-base:production
  stage: test
  allow_failure: true
  # dependencies:
  #   - install_dependencies
  script:
    # - pnpm test -- --ci  # Run Jest tests with the --ci flag for CI environment
    - ./run.sh $TEST_SCOPE
  artifacts:
    paths:
      - allure-results/
    when: always

generate_allure_report:
  image: 149062447078.dkr.ecr.ap-southeast-1.amazonaws.com/cicd/qa-base:production
  stage: report
  dependencies:
    - run_tests
  script:
    - |
      if [ ! -d allure-results ]; then
        echo "Error: allure-results directory does not exist!"
        exit 1
      fi
    - allure generate allure-results --clean
    - ls -lh allure-report
  artifacts:
    paths:
      - allure-report/  # Store the allure report for download

# Upload Allure Report to S3 bucket
upload_to_s3:
  image: 
    name: amazon/aws-cli:latest
    entrypoint: [""]
  stage: upload
  dependencies:
    - generate_allure_report  # Ensure the report is generated before uploading
  script:
    - ls -lh /root/.aws
    - cat /root/.aws/config
    - export FOLDER_NAME=$(TZ="Asia/Singapore" date +"%Y%m%d_%H%M%S")SGT
    - aws s3 cp allure-report/ s3://allure-static-dev/reports/$FOLDER_NAME --recursive
    - echo "Link to report - http://allure-static-dev.s3-website-ap-southeast-1.amazonaws.com/reports/$FOLDER_NAME"
    - echo "REPORT_LINK=http://allure-static-dev.s3-website-ap-southeast-1.amazonaws.com/reports/$FOLDER_NAME" > variables.env
  artifacts:
    reports:
      dotenv: variables.env  # Pass the dotenv file to the next job

send_slack_notification:
  stage: notify
  dependencies:
    - upload_to_s3
  needs: 
    job: upload_to_s3
    artifacts: true
  before_script:
    - export $(< variables.env)
  script:
    # - source exports.env  # Load the variables from the .env file
    - echo "Sending slack notification $REPORT_LINK"
    - >
      RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST $SLACK_WEBHOOK_URL \
        -H "Content-Type: application/json" \
        -d '{"text": "Deployment has finished successfully! \n $REPORT_LINK"}')
      if [ "$RESPONSE" -ne 200 ]; then
        echo "Webhook request failed with status $RESPONSE"
        exit 1
      fi
