# GENERAL #
# only support demo account for prod
password_demo: gAAAAABoWMEt4Qc6bYKgPVXrbV3IuZjE_EJr1mE3aiqKPdG-oKPN462pDvi19zh-tkySetZtvasVQXlhuN1KqkCUz63-eyYQhg==

# mobile
android_udid: ""
ios_udid: ""

lirunex:
  base_url: https://webtrader.lirunex.com

  credentials:
    mt4:
      user_demo: 2092012616

    mt5:
      user_demo: 569205536

  mobile:
    app_package: com.aquariux.wt.lirunex
    app_bundle: ...

dcode:
  base_url: https://webtrader.dcodemarkets.com

  credentials:
    mt5:
      user_live: 7003091
      user_demo: 7003091

  mobile:
    app_package: com.aquariux.wt.uat.dcodemarkets
    app_bundle: ...
