# Chart Data API Testing Configuration - SIT Environment

password_crm: Auto@12345
password_live: Autotest@12345
password_demo: Autotest@12345

# Lirunex Client Configuration
lirunex:
  api_url: https://lirunex-mb.webtrader-sit.s20ip12.com/api
  
  credentials:
    mt4:
      user_crm: mt4_automation28@mailinator.com
      user_demo: 2092010247
    mt5:
      user_crm: mt5_automation28@mailinator.com
      user_demo: 569202036

# TransactCloud Client Configuration
transactCloud:
  api_url: https://transactcloudmt5-mb.webtrader-sit.s20ip12.com/api
  
  credentials:
    mt5:
      user_live: 998771
      user_demo: 998771
