# GENERAL #


root_url: https://root.webtrader-uat.s20ip12.com/root
user_root: root
password_root: gAAAAABoWMPeEuKg4PHTx1nmw8Yr8oFib99waFf1Exk6ZVh12xoSYt0E42lywgKOXeEg4nog2V2seRABXv8IsHntNSL-PHHN0g==

password_crm: gAAAAABoWMEXslfQb9KOlvT7GjPiMPOc1cQEVZjrI--VDYHBQHsywhk_AYGjyYv7zpTS51BJ7TyQY7J1unco_TQlE_SqRJX-TQ==
password_live: gAAAAABoWMEt4Qc6bYKgPVXrbV3IuZjE_EJr1mE3aiqKPdG-oKPN462pDvi19zh-tkySetZtvasVQXlhuN1KqkCUz63-eyYQhg==
password_demo: gAAAAABoWMEt4Qc6bYKgPVXrbV3IuZjE_EJr1mE3aiqKPdG-oKPN462pDvi19zh-tkySetZtvasVQXlhuN1KqkCUz63-eyYQhg==

# mobile
android_udid: ""
ios_udid: ""


lirunex:
  base_url: https://lirunex-mb.webtrader-uat.s20ip12.com
  bo_url: https://lirunex-backoffice.webtrader-uat.s20ip12.com/backoffice

  credentials:
    mt4:
      # user_live: ...
      user_crm: mt4_automation30@mailinator.com
      user_demo: 2092009642

    mt5:
      # user_live: ...
      user_crm: mt5_automation31@mailinator.com
      user_demo: 569203282

  mobile:
    app_package: com.aquariux.lirunex.uat
    app_bundle: com.aquariux.lirunex.uat

transactCloud:
  base_url: https://transactcloudmt5-mb.webtrader-uat.s20ip12.com
  bo_url: https://transactcloudmt5-backoffice.webtrader-uat.s20ip12.com/backoffice/

  credentials:
    mt5:
      user_live: 998931
      user_demo: 998931

  mobile:
    app_package: com.aquariux.wt.uat.transactcloudmt5
    app_bundle: com.aquariux.wt.uat.transactcloudmt5
